### ISSUE TITLE
Création Boulut

### ISSUE THREAD

**Issue by Pangoraw** [simde-utc/gesasso2#18]
Boulut est un club qui organise des regroupements autour de la pétanque.
Login asso : boulut
Action a realiser :
- [ ] Reset password asso
- [ ] Reset password sql
- [X] Creation asso
- [ ] Suppression asso
- [ ] Autre

**Comment by cesar-richard** [comment]
Asso créée , fct à tester, Clément contacté, portail a debug

**Comment by cesar-richard** [comment]
Ok portail
